name:                crisp8
version:             0.1.0.0
github:              "lpraz/crisp8"
license:             BSD3
author:              "Logan Praznik"
maintainer:          "example@example.com"
copyright:           "2020 Author name here"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/lpraz/crisp8#readme>

dependencies:
- base >= 4.7 && < 5
- linear
- sdl2
- bytestring
- array
- random

library:
  source-dirs: src

executables:
  crisp8-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crisp8

tests:
  crisp8-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - crisp8
